site_name: Fpart.org
site_url: http://www.fpart.org
repo_url: https://github.com/martymac/fpart
edit_uri: edit/master/docs/www.fpart.org/docs
nav:
    - Home: index.md
    - Fpart: fpart.md
    - Fpsync: fpsync.md
    - Changelog: changelog.md
    - Links: links.md
# See: https://mkdocs.github.io/mkdocs-bootswatch/#litera
theme: litera
markdown_extensions:
    - attr_list
